# iluvgirlswithglasses' kitty

spacing         = 2
padding         = 2
hide_ascii      = false
separator       = " "
key_color       = "#F07489"
separator_color = "#C6D0F5"

[custom_ascii]
color           = "#C6D0F5"
path            = "~/.config/macchina/ascii-cat.txt"

[box]
border          = "plain"
visible         = false

[palette]
type            = "Light"
glyph           = " ● "
visible         = true

[bar]
glyph           = "●"
symbol_open     = '('
symbol_close    = ')'
visible         = true
hide_delimiters = true

[box.inner_margin]
x               = 2
y               = 1

[randomize]
key_color       = false
separator_color = false
pool            = "base"

[keys]
host            = "host"
kernel          = "kernel"
battery         = "battery"
os              = "os"
de              = "de"
wm              = "wm"
distro          = "os"
terminal        = "terminal"
shell           = "shell"
packages        = "packages"
uptime          = "uptime"
memory          = "memory"
machine         = "machine"
resolution      = "resolution"
cpu_load        = "cpu"
cpu             = "cpu"
